// Generated by CoffeeScript 1.9.3
(function() {
  var deps;

  deps = ['d3', 'BarGraph'];

  define(deps, function(d3, BarGraph) {
    var btOnly, graph, layers, properties;
    properties = {
      width: 600,
      height: 500,
      margin: {
        right: 50,
        left: 50,
        top: 50,
        bottom: 100
      },
      year: '2000',
      tooltip: d3.select('body').append('div').attr('class', 'tooltip').attr('opacity', 0)
    };
    graph = [];
    layers = [];
    btOnly = d3.select('#bt-only').attr('width', properties.width).attr('height', properties.height).append('g').attr('transform', 'translate(' + properties.margin.left + ',' + properties.margin.right + ')');
    d3.csv('./dat/bt-only.csv', function(error, csv) {
      if (error != null) {
        console.error(error);
      }
      layers[0] = csv;
      graph[0] = new BarGraph(csv, properties, btOnly);
      return graph[0].propogateUpdate();
    });
    d3.csv('./dat/herbicide-only.csv', function(error, csv) {
      if (error != null) {
        console.error(error);
      }
      return layers[1] = csv;
    });
    d3.csv('./dat/stacked-gene.csv', function(error, csv) {
      if (error != null) {
        console.error(error);
      }
      return layers[2] = csv;
    });
    return d3.csv('./dat/all-ge.csv', function(error, csv) {
      if (error != null) {
        console.error(error);
      }
      layers[3] = csv;
      return console.log(layers);
    });
  });

}).call(this);
